---
# tasks file for java
- name: Download Java SE 8u45
  shell: 'wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/{{major}}u{{minor}}-b{{build}}/jdk-{{major}}u{{minor}}-linux-x64.tar.gz" chdir=/opt creates=jdk-{{major}}u{{minor}}-linux-x64.tar.gz'
- name: Unarchive JDK
  shell: tar xvzf jdk-{{major}}u{{minor}}-linux-x64.tar.gz chdir=/opt creates=jdk1.{{major}}.0_{{minor}}
- name: Set alternatives for java
  alternatives: path=/opt/jdk1.{{major}}.0_{{minor}}/bin/java name=java link=/usr/bin/java
- name: Set alternatives for javac
  alternatives: path=/opt/jdk1.{{major}}.0_{{minor}}/bin/javac name=javac link=/usr/bin/javac
- name: Set alternatives for jar
  alternatives: path=/opt/jdk1.{{major}}.0_{{minor}}/bin/jar name=jar link=/usr/bin/jar
- name: Set JAVA_HOME
  lineinfile: dest=/etc/environment regexp=^JAVA_HOME line=JAVA_HOME="/opt/jdk1.{{major}}.0_{{minor}}" state=present
- name: Set JRE_HOME
  lineinfile: dest=/etc/environment regexp=^JRE_HOME line=JRE_HOME="/opt/jdk1.{{major}}.0_{{minor}}/jre" state=present
